// Generated by gencpp from file lxind_msgs/CertificateInfos.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_CERTIFICATEINFOS_H
#define LXIND_MSGS_MESSAGE_CERTIFICATEINFOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lxind_msgs/CertificateInfo.h>

namespace lxind_msgs
{
template <class ContainerAllocator>
struct CertificateInfos_
{
  typedef CertificateInfos_<ContainerAllocator> Type;

  CertificateInfos_()
    : infos()  {
    }
  CertificateInfos_(const ContainerAllocator& _alloc)
    : infos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::lxind_msgs::CertificateInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lxind_msgs::CertificateInfo_<ContainerAllocator> >::other >  _infos_type;
  _infos_type infos;





  typedef boost::shared_ptr< ::lxind_msgs::CertificateInfos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::CertificateInfos_<ContainerAllocator> const> ConstPtr;

}; // struct CertificateInfos_

typedef ::lxind_msgs::CertificateInfos_<std::allocator<void> > CertificateInfos;

typedef boost::shared_ptr< ::lxind_msgs::CertificateInfos > CertificateInfosPtr;
typedef boost::shared_ptr< ::lxind_msgs::CertificateInfos const> CertificateInfosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::CertificateInfos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::CertificateInfos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::CertificateInfos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::CertificateInfos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::CertificateInfos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::CertificateInfos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::CertificateInfos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::CertificateInfos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::CertificateInfos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86a25173dc2ad721a4f1ce4f2a9ec294";
  }

  static const char* value(const ::lxind_msgs::CertificateInfos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86a25173dc2ad721ULL;
  static const uint64_t static_value2 = 0xa4f1ce4f2a9ec294ULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::CertificateInfos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/CertificateInfos";
  }

  static const char* value(const ::lxind_msgs::CertificateInfos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::CertificateInfos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
lxind_msgs/CertificateInfo[] infos\n\
================================================================================\n\
MSG: lxind_msgs/CertificateInfo\n\
string info_type\n\
string info_detail\n\
";
  }

  static const char* value(const ::lxind_msgs::CertificateInfos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::CertificateInfos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.infos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CertificateInfos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::CertificateInfos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::CertificateInfos_<ContainerAllocator>& v)
  {
    s << indent << "infos[]" << std::endl;
    for (size_t i = 0; i < v.infos.size(); ++i)
    {
      s << indent << "  infos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lxind_msgs::CertificateInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.infos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_CERTIFICATEINFOS_H
