// Generated by gencpp from file lxind_msgs/GetFootprintSizeResponse.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_GETFOOTPRINTSIZERESPONSE_H
#define LXIND_MSGS_MESSAGE_GETFOOTPRINTSIZERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lxind_msgs
{
template <class ContainerAllocator>
struct GetFootprintSizeResponse_
{
  typedef GetFootprintSizeResponse_<ContainerAllocator> Type;

  GetFootprintSizeResponse_()
    : width(0.0)
    , height(0.0)  {
    }
  GetFootprintSizeResponse_(const ContainerAllocator& _alloc)
    : width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFootprintSizeResponse_

typedef ::lxind_msgs::GetFootprintSizeResponse_<std::allocator<void> > GetFootprintSizeResponse;

typedef boost::shared_ptr< ::lxind_msgs::GetFootprintSizeResponse > GetFootprintSizeResponsePtr;
typedef boost::shared_ptr< ::lxind_msgs::GetFootprintSizeResponse const> GetFootprintSizeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f86522e647336fb10b55359fe003f673";
  }

  static const char* value(const ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf86522e647336fb1ULL;
  static const uint64_t static_value2 = 0x0b55359fe003f673ULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/GetFootprintSizeResponse";
  }

  static const char* value(const ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 width\n\
float64 height\n\
\n\
";
  }

  static const char* value(const ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFootprintSizeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::GetFootprintSizeResponse_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_GETFOOTPRINTSIZERESPONSE_H
