// Generated by gencpp from file lxind_msgs/GetNavStatus.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_GETNAVSTATUS_H
#define LXIND_MSGS_MESSAGE_GETNAVSTATUS_H

#include <ros/service_traits.h>


#include <lxind_msgs/GetNavStatusRequest.h>
#include <lxind_msgs/GetNavStatusResponse.h>


namespace lxind_msgs
{

struct GetNavStatus
{

typedef GetNavStatusRequest Request;
typedef GetNavStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNavStatus
} // namespace lxind_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lxind_msgs::GetNavStatus > {
  static const char* value()
  {
    return "db378f79657e7f13f64098eef9409889";
  }

  static const char* value(const ::lxind_msgs::GetNavStatus&) { return value(); }
};

template<>
struct DataType< ::lxind_msgs::GetNavStatus > {
  static const char* value()
  {
    return "lxind_msgs/GetNavStatus";
  }

  static const char* value(const ::lxind_msgs::GetNavStatus&) { return value(); }
};


// service_traits::MD5Sum< ::lxind_msgs::GetNavStatusRequest> should match 
// service_traits::MD5Sum< ::lxind_msgs::GetNavStatus > 
template<>
struct MD5Sum< ::lxind_msgs::GetNavStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::GetNavStatus >::value();
  }
  static const char* value(const ::lxind_msgs::GetNavStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::GetNavStatusRequest> should match 
// service_traits::DataType< ::lxind_msgs::GetNavStatus > 
template<>
struct DataType< ::lxind_msgs::GetNavStatusRequest>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::GetNavStatus >::value();
  }
  static const char* value(const ::lxind_msgs::GetNavStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lxind_msgs::GetNavStatusResponse> should match 
// service_traits::MD5Sum< ::lxind_msgs::GetNavStatus > 
template<>
struct MD5Sum< ::lxind_msgs::GetNavStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::GetNavStatus >::value();
  }
  static const char* value(const ::lxind_msgs::GetNavStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::GetNavStatusResponse> should match 
// service_traits::DataType< ::lxind_msgs::GetNavStatus > 
template<>
struct DataType< ::lxind_msgs::GetNavStatusResponse>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::GetNavStatus >::value();
  }
  static const char* value(const ::lxind_msgs::GetNavStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_GETNAVSTATUS_H
