// Generated by gencpp from file lxind_msgs/GetRealDataRequest.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_GETREALDATAREQUEST_H
#define LXIND_MSGS_MESSAGE_GETREALDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lxind_msgs
{
template <class ContainerAllocator>
struct GetRealDataRequest_
{
  typedef GetRealDataRequest_<ContainerAllocator> Type;

  GetRealDataRequest_()
    : dataJson()  {
    }
  GetRealDataRequest_(const ContainerAllocator& _alloc)
    : dataJson(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dataJson_type;
  _dataJson_type dataJson;





  typedef boost::shared_ptr< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetRealDataRequest_

typedef ::lxind_msgs::GetRealDataRequest_<std::allocator<void> > GetRealDataRequest;

typedef boost::shared_ptr< ::lxind_msgs::GetRealDataRequest > GetRealDataRequestPtr;
typedef boost::shared_ptr< ::lxind_msgs::GetRealDataRequest const> GetRealDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c3c2532ef978f111ed3b999d7cf539e";
  }

  static const char* value(const ::lxind_msgs::GetRealDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c3c2532ef978f11ULL;
  static const uint64_t static_value2 = 0x1ed3b999d7cf539eULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/GetRealDataRequest";
  }

  static const char* value(const ::lxind_msgs::GetRealDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string dataJson\n\
";
  }

  static const char* value(const ::lxind_msgs::GetRealDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dataJson);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRealDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::GetRealDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::GetRealDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "dataJson: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dataJson);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_GETREALDATAREQUEST_H
