// Generated by gencpp from file lxind_msgs/image.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_IMAGE_H
#define LXIND_MSGS_MESSAGE_IMAGE_H

#include <ros/service_traits.h>


#include <lxind_msgs/imageRequest.h>
#include <lxind_msgs/imageResponse.h>


namespace lxind_msgs
{

struct image
{

typedef imageRequest Request;
typedef imageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct image
} // namespace lxind_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lxind_msgs::image > {
  static const char* value()
  {
    return "b23513ba12c260b320c4ce474701b6c5";
  }

  static const char* value(const ::lxind_msgs::image&) { return value(); }
};

template<>
struct DataType< ::lxind_msgs::image > {
  static const char* value()
  {
    return "lxind_msgs/image";
  }

  static const char* value(const ::lxind_msgs::image&) { return value(); }
};


// service_traits::MD5Sum< ::lxind_msgs::imageRequest> should match 
// service_traits::MD5Sum< ::lxind_msgs::image > 
template<>
struct MD5Sum< ::lxind_msgs::imageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::image >::value();
  }
  static const char* value(const ::lxind_msgs::imageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::imageRequest> should match 
// service_traits::DataType< ::lxind_msgs::image > 
template<>
struct DataType< ::lxind_msgs::imageRequest>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::image >::value();
  }
  static const char* value(const ::lxind_msgs::imageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lxind_msgs::imageResponse> should match 
// service_traits::MD5Sum< ::lxind_msgs::image > 
template<>
struct MD5Sum< ::lxind_msgs::imageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::image >::value();
  }
  static const char* value(const ::lxind_msgs::imageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::imageResponse> should match 
// service_traits::DataType< ::lxind_msgs::image > 
template<>
struct DataType< ::lxind_msgs::imageResponse>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::image >::value();
  }
  static const char* value(const ::lxind_msgs::imageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_IMAGE_H
