// Generated by gencpp from file lxind_msgs/imageRequest.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_IMAGEREQUEST_H
#define LXIND_MSGS_MESSAGE_IMAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lxind_msgs
{
template <class ContainerAllocator>
struct imageRequest_
{
  typedef imageRequest_<ContainerAllocator> Type;

  imageRequest_()
    : get_image(0)  {
    }
  imageRequest_(const ContainerAllocator& _alloc)
    : get_image(0)  {
  (void)_alloc;
    }



   typedef int64_t _get_image_type;
  _get_image_type get_image;





  typedef boost::shared_ptr< ::lxind_msgs::imageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::imageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct imageRequest_

typedef ::lxind_msgs::imageRequest_<std::allocator<void> > imageRequest;

typedef boost::shared_ptr< ::lxind_msgs::imageRequest > imageRequestPtr;
typedef boost::shared_ptr< ::lxind_msgs::imageRequest const> imageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::imageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::imageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::imageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::imageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::imageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::imageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::imageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::imageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::imageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c672f9f05a33a9da0b0eefb3c323d0c4";
  }

  static const char* value(const ::lxind_msgs::imageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc672f9f05a33a9daULL;
  static const uint64_t static_value2 = 0x0b0eefb3c323d0c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::imageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/imageRequest";
  }

  static const char* value(const ::lxind_msgs::imageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::imageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 get_image\n\
";
  }

  static const char* value(const ::lxind_msgs::imageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::imageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get_image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::imageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::imageRequest_<ContainerAllocator>& v)
  {
    s << indent << "get_image: ";
    Printer<int64_t>::stream(s, indent + "  ", v.get_image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_IMAGEREQUEST_H
