// Generated by gencpp from file lxind_msgs/InitializeLocStatus.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_INITIALIZELOCSTATUS_H
#define LXIND_MSGS_MESSAGE_INITIALIZELOCSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lxind_msgs/InitializeLoc.h>

namespace lxind_msgs
{
template <class ContainerAllocator>
struct InitializeLocStatus_
{
  typedef InitializeLocStatus_<ContainerAllocator> Type;

  InitializeLocStatus_()
    : isSuccess(false)
    , weight(0)
    , relocInfo()  {
    }
  InitializeLocStatus_(const ContainerAllocator& _alloc)
    : isSuccess(false)
    , weight(0)
    , relocInfo(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _isSuccess_type;
  _isSuccess_type isSuccess;

   typedef int32_t _weight_type;
  _weight_type weight;

   typedef  ::lxind_msgs::InitializeLoc_<ContainerAllocator>  _relocInfo_type;
  _relocInfo_type relocInfo;





  typedef boost::shared_ptr< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> const> ConstPtr;

}; // struct InitializeLocStatus_

typedef ::lxind_msgs::InitializeLocStatus_<std::allocator<void> > InitializeLocStatus;

typedef boost::shared_ptr< ::lxind_msgs::InitializeLocStatus > InitializeLocStatusPtr;
typedef boost::shared_ptr< ::lxind_msgs::InitializeLocStatus const> InitializeLocStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d6cace685863e5309090db1004f6f1c";
  }

  static const char* value(const ::lxind_msgs::InitializeLocStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d6cace685863e53ULL;
  static const uint64_t static_value2 = 0x09090db1004f6f1cULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/InitializeLocStatus";
  }

  static const char* value(const ::lxind_msgs::InitializeLocStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isSuccess\n\
int32 weight\n\
InitializeLoc relocInfo\n\
================================================================================\n\
MSG: lxind_msgs/InitializeLoc\n\
Header header\n\
string name\n\
float32 x\n\
float32 y\n\
float32 theta\n\
bool is_startup_reloc\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::lxind_msgs::InitializeLocStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isSuccess);
      stream.next(m.weight);
      stream.next(m.relocInfo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitializeLocStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::InitializeLocStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::InitializeLocStatus_<ContainerAllocator>& v)
  {
    s << indent << "isSuccess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isSuccess);
    s << indent << "weight: ";
    Printer<int32_t>::stream(s, indent + "  ", v.weight);
    s << indent << "relocInfo: ";
    s << std::endl;
    Printer< ::lxind_msgs::InitializeLoc_<ContainerAllocator> >::stream(s, indent + "  ", v.relocInfo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_INITIALIZELOCSTATUS_H
