// Generated by gencpp from file lxind_msgs/pose.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_POSE_H
#define LXIND_MSGS_MESSAGE_POSE_H

#include <ros/service_traits.h>


#include <lxind_msgs/poseRequest.h>
#include <lxind_msgs/poseResponse.h>


namespace lxind_msgs
{

struct pose
{

typedef poseRequest Request;
typedef poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose
} // namespace lxind_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lxind_msgs::pose > {
  static const char* value()
  {
    return "2c6f431f1b0c52ae4c85948feb8a7704";
  }

  static const char* value(const ::lxind_msgs::pose&) { return value(); }
};

template<>
struct DataType< ::lxind_msgs::pose > {
  static const char* value()
  {
    return "lxind_msgs/pose";
  }

  static const char* value(const ::lxind_msgs::pose&) { return value(); }
};


// service_traits::MD5Sum< ::lxind_msgs::poseRequest> should match 
// service_traits::MD5Sum< ::lxind_msgs::pose > 
template<>
struct MD5Sum< ::lxind_msgs::poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::pose >::value();
  }
  static const char* value(const ::lxind_msgs::poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::poseRequest> should match 
// service_traits::DataType< ::lxind_msgs::pose > 
template<>
struct DataType< ::lxind_msgs::poseRequest>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::pose >::value();
  }
  static const char* value(const ::lxind_msgs::poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lxind_msgs::poseResponse> should match 
// service_traits::MD5Sum< ::lxind_msgs::pose > 
template<>
struct MD5Sum< ::lxind_msgs::poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::pose >::value();
  }
  static const char* value(const ::lxind_msgs::poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::poseResponse> should match 
// service_traits::DataType< ::lxind_msgs::pose > 
template<>
struct DataType< ::lxind_msgs::poseResponse>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::pose >::value();
  }
  static const char* value(const ::lxind_msgs::poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_POSE_H
