// Generated by gencpp from file lxind_msgs/QueryPathAvail.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_QUERYPATHAVAIL_H
#define LXIND_MSGS_MESSAGE_QUERYPATHAVAIL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lxind_msgs
{
template <class ContainerAllocator>
struct QueryPathAvail_
{
  typedef QueryPathAvail_<ContainerAllocator> Type;

  QueryPathAvail_()
    : header()
    , session_id(0)
    , path_nodes()  {
    }
  QueryPathAvail_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , session_id(0)
    , path_nodes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _session_id_type;
  _session_id_type session_id;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _path_nodes_type;
  _path_nodes_type path_nodes;





  typedef boost::shared_ptr< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> const> ConstPtr;

}; // struct QueryPathAvail_

typedef ::lxind_msgs::QueryPathAvail_<std::allocator<void> > QueryPathAvail;

typedef boost::shared_ptr< ::lxind_msgs::QueryPathAvail > QueryPathAvailPtr;
typedef boost::shared_ptr< ::lxind_msgs::QueryPathAvail const> QueryPathAvailConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::QueryPathAvail_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0bb42d59bd907f57ed37938d4d824a0";
  }

  static const char* value(const ::lxind_msgs::QueryPathAvail_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0bb42d59bd907f5ULL;
  static const uint64_t static_value2 = 0x7ed37938d4d824a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/QueryPathAvail";
  }

  static const char* value(const ::lxind_msgs::QueryPathAvail_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint32 session_id\n\
\n\
string[] path_nodes\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::lxind_msgs::QueryPathAvail_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.session_id);
      stream.next(m.path_nodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryPathAvail_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::QueryPathAvail_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::QueryPathAvail_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "session_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.session_id);
    s << indent << "path_nodes[]" << std::endl;
    for (size_t i = 0; i < v.path_nodes.size(); ++i)
    {
      s << indent << "  path_nodes[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path_nodes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_QUERYPATHAVAIL_H
