// Generated by gencpp from file lxind_msgs/RawBaseSensorData.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_RAWBASESENSORDATA_H
#define LXIND_MSGS_MESSAGE_RAWBASESENSORDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lxind_msgs
{
template <class ContainerAllocator>
struct RawBaseSensorData_
{
  typedef RawBaseSensorData_<ContainerAllocator> Type;

  RawBaseSensorData_()
    : header()
    , left_encoder(0)
    , right_encoder(0)
    , yaw(0.0)
    , is_bumped(false)
    , emerg_pressed(false)
    , switch1_on(false)
    , switch2_on(false)
    , switch3_on(false)  {
    }
  RawBaseSensorData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_encoder(0)
    , right_encoder(0)
    , yaw(0.0)
    , is_bumped(false)
    , emerg_pressed(false)
    , switch1_on(false)
    , switch2_on(false)
    , switch3_on(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _left_encoder_type;
  _left_encoder_type left_encoder;

   typedef int32_t _right_encoder_type;
  _right_encoder_type right_encoder;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef uint8_t _is_bumped_type;
  _is_bumped_type is_bumped;

   typedef uint8_t _emerg_pressed_type;
  _emerg_pressed_type emerg_pressed;

   typedef uint8_t _switch1_on_type;
  _switch1_on_type switch1_on;

   typedef uint8_t _switch2_on_type;
  _switch2_on_type switch2_on;

   typedef uint8_t _switch3_on_type;
  _switch3_on_type switch3_on;





  typedef boost::shared_ptr< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> const> ConstPtr;

}; // struct RawBaseSensorData_

typedef ::lxind_msgs::RawBaseSensorData_<std::allocator<void> > RawBaseSensorData;

typedef boost::shared_ptr< ::lxind_msgs::RawBaseSensorData > RawBaseSensorDataPtr;
typedef boost::shared_ptr< ::lxind_msgs::RawBaseSensorData const> RawBaseSensorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a215546cf8369a7c4083a9a14c8c42a";
  }

  static const char* value(const ::lxind_msgs::RawBaseSensorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a215546cf8369a7ULL;
  static const uint64_t static_value2 = 0xc4083a9a14c8c42aULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/RawBaseSensorData";
  }

  static const char* value(const ::lxind_msgs::RawBaseSensorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# raw values reported from base controller\n\
Header header\n\
\n\
int32 left_encoder\n\
int32 right_encoder\n\
float32 yaw\n\
bool is_bumped\n\
bool emerg_pressed\n\
\n\
bool switch1_on\n\
bool switch2_on\n\
bool switch3_on\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::lxind_msgs::RawBaseSensorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_encoder);
      stream.next(m.right_encoder);
      stream.next(m.yaw);
      stream.next(m.is_bumped);
      stream.next(m.emerg_pressed);
      stream.next(m.switch1_on);
      stream.next(m.switch2_on);
      stream.next(m.switch3_on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RawBaseSensorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::RawBaseSensorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::RawBaseSensorData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_encoder);
    s << indent << "right_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_encoder);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "is_bumped: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_bumped);
    s << indent << "emerg_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emerg_pressed);
    s << indent << "switch1_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.switch1_on);
    s << indent << "switch2_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.switch2_on);
    s << indent << "switch3_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.switch3_on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_RAWBASESENSORDATA_H
