// Generated by gencpp from file lxind_msgs/SendElevCtrlRequest.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_SENDELEVCTRLREQUEST_H
#define LXIND_MSGS_MESSAGE_SENDELEVCTRLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lxind_msgs
{
template <class ContainerAllocator>
struct SendElevCtrlRequest_
{
  typedef SendElevCtrlRequest_<ContainerAllocator> Type;

  SendElevCtrlRequest_()
    : cmd(0)  {
    }
  SendElevCtrlRequest_(const ContainerAllocator& _alloc)
    : cmd(0)  {
  (void)_alloc;
    }



   typedef uint8_t _cmd_type;
  _cmd_type cmd;



  enum {
    ELEV_NOACTION = 0u,
    ELEV_UP = 1u,
    ELEV_DOWN = 2u,
    ELEV_STOP = 3u,
    ELEV_CLEAR = 4u,
    ELEV_RESET = 5u,
  };


  typedef boost::shared_ptr< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendElevCtrlRequest_

typedef ::lxind_msgs::SendElevCtrlRequest_<std::allocator<void> > SendElevCtrlRequest;

typedef boost::shared_ptr< ::lxind_msgs::SendElevCtrlRequest > SendElevCtrlRequestPtr;
typedef boost::shared_ptr< ::lxind_msgs::SendElevCtrlRequest const> SendElevCtrlRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a8403831377bf4e356597f9718a77e3";
  }

  static const char* value(const ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a8403831377bf4eULL;
  static const uint64_t static_value2 = 0x356597f9718a77e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/SendElevCtrlRequest";
  }

  static const char* value(const ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ELEV_NOACTION = 0\n\
uint8 ELEV_UP = 1\n\
uint8 ELEV_DOWN = 2\n\
uint8 ELEV_STOP = 3\n\
uint8 ELEV_CLEAR = 4\n\
uint8 ELEV_RESET = 5\n\
\n\
uint8 cmd\n\
";
  }

  static const char* value(const ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendElevCtrlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::SendElevCtrlRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_SENDELEVCTRLREQUEST_H
