// Generated by gencpp from file lxind_msgs/SendElevCtrlResponse.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_SENDELEVCTRLRESPONSE_H
#define LXIND_MSGS_MESSAGE_SENDELEVCTRLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lxind_msgs
{
template <class ContainerAllocator>
struct SendElevCtrlResponse_
{
  typedef SendElevCtrlResponse_<ContainerAllocator> Type;

  SendElevCtrlResponse_()
    : ret_msg()  {
    }
  SendElevCtrlResponse_(const ContainerAllocator& _alloc)
    : ret_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ret_msg_type;
  _ret_msg_type ret_msg;





  typedef boost::shared_ptr< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SendElevCtrlResponse_

typedef ::lxind_msgs::SendElevCtrlResponse_<std::allocator<void> > SendElevCtrlResponse;

typedef boost::shared_ptr< ::lxind_msgs::SendElevCtrlResponse > SendElevCtrlResponsePtr;
typedef boost::shared_ptr< ::lxind_msgs::SendElevCtrlResponse const> SendElevCtrlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fccccc533ea484677a8d17d860146522";
  }

  static const char* value(const ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfccccc533ea48467ULL;
  static const uint64_t static_value2 = 0x7a8d17d860146522ULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/SendElevCtrlResponse";
  }

  static const char* value(const ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ret_msg\n\
";
  }

  static const char* value(const ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendElevCtrlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::SendElevCtrlResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ret_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_SENDELEVCTRLRESPONSE_H
