// Generated by gencpp from file lxind_msgs/SendSubTask.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_SENDSUBTASK_H
#define LXIND_MSGS_MESSAGE_SENDSUBTASK_H

#include <ros/service_traits.h>


#include <lxind_msgs/SendSubTaskRequest.h>
#include <lxind_msgs/SendSubTaskResponse.h>


namespace lxind_msgs
{

struct SendSubTask
{

typedef SendSubTaskRequest Request;
typedef SendSubTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendSubTask
} // namespace lxind_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lxind_msgs::SendSubTask > {
  static const char* value()
  {
    return "ded50bd33fc998583d1657965f147705";
  }

  static const char* value(const ::lxind_msgs::SendSubTask&) { return value(); }
};

template<>
struct DataType< ::lxind_msgs::SendSubTask > {
  static const char* value()
  {
    return "lxind_msgs/SendSubTask";
  }

  static const char* value(const ::lxind_msgs::SendSubTask&) { return value(); }
};


// service_traits::MD5Sum< ::lxind_msgs::SendSubTaskRequest> should match 
// service_traits::MD5Sum< ::lxind_msgs::SendSubTask > 
template<>
struct MD5Sum< ::lxind_msgs::SendSubTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::SendSubTask >::value();
  }
  static const char* value(const ::lxind_msgs::SendSubTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::SendSubTaskRequest> should match 
// service_traits::DataType< ::lxind_msgs::SendSubTask > 
template<>
struct DataType< ::lxind_msgs::SendSubTaskRequest>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::SendSubTask >::value();
  }
  static const char* value(const ::lxind_msgs::SendSubTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lxind_msgs::SendSubTaskResponse> should match 
// service_traits::MD5Sum< ::lxind_msgs::SendSubTask > 
template<>
struct MD5Sum< ::lxind_msgs::SendSubTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::SendSubTask >::value();
  }
  static const char* value(const ::lxind_msgs::SendSubTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::SendSubTaskResponse> should match 
// service_traits::DataType< ::lxind_msgs::SendSubTask > 
template<>
struct DataType< ::lxind_msgs::SendSubTaskResponse>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::SendSubTask >::value();
  }
  static const char* value(const ::lxind_msgs::SendSubTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_SENDSUBTASK_H
