// Generated by gencpp from file lxind_msgs/SendElevCtrl.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_SENDELEVCTRL_H
#define LXIND_MSGS_MESSAGE_SENDELEVCTRL_H

#include <ros/service_traits.h>


#include <lxind_msgs/SendElevCtrlRequest.h>
#include <lxind_msgs/SendElevCtrlResponse.h>


namespace lxind_msgs
{

struct SendElevCtrl
{

typedef SendElevCtrlRequest Request;
typedef SendElevCtrlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendElevCtrl
} // namespace lxind_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lxind_msgs::SendElevCtrl > {
  static const char* value()
  {
    return "f5f151d913835fc1ca9ebf1643791e6c";
  }

  static const char* value(const ::lxind_msgs::SendElevCtrl&) { return value(); }
};

template<>
struct DataType< ::lxind_msgs::SendElevCtrl > {
  static const char* value()
  {
    return "lxind_msgs/SendElevCtrl";
  }

  static const char* value(const ::lxind_msgs::SendElevCtrl&) { return value(); }
};


// service_traits::MD5Sum< ::lxind_msgs::SendElevCtrlRequest> should match 
// service_traits::MD5Sum< ::lxind_msgs::SendElevCtrl > 
template<>
struct MD5Sum< ::lxind_msgs::SendElevCtrlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::SendElevCtrl >::value();
  }
  static const char* value(const ::lxind_msgs::SendElevCtrlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::SendElevCtrlRequest> should match 
// service_traits::DataType< ::lxind_msgs::SendElevCtrl > 
template<>
struct DataType< ::lxind_msgs::SendElevCtrlRequest>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::SendElevCtrl >::value();
  }
  static const char* value(const ::lxind_msgs::SendElevCtrlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lxind_msgs::SendElevCtrlResponse> should match 
// service_traits::MD5Sum< ::lxind_msgs::SendElevCtrl > 
template<>
struct MD5Sum< ::lxind_msgs::SendElevCtrlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::SendElevCtrl >::value();
  }
  static const char* value(const ::lxind_msgs::SendElevCtrlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::SendElevCtrlResponse> should match 
// service_traits::DataType< ::lxind_msgs::SendElevCtrl > 
template<>
struct DataType< ::lxind_msgs::SendElevCtrlResponse>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::SendElevCtrl >::value();
  }
  static const char* value(const ::lxind_msgs::SendElevCtrlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_SENDELEVCTRL_H
