// Generated by gencpp from file lxind_msgs/SendDistAndAngle.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_SENDDISTANDANGLE_H
#define LXIND_MSGS_MESSAGE_SENDDISTANDANGLE_H

#include <ros/service_traits.h>


#include <lxind_msgs/SendDistAndAngleRequest.h>
#include <lxind_msgs/SendDistAndAngleResponse.h>


namespace lxind_msgs
{

struct SendDistAndAngle
{

typedef SendDistAndAngleRequest Request;
typedef SendDistAndAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendDistAndAngle
} // namespace lxind_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lxind_msgs::SendDistAndAngle > {
  static const char* value()
  {
    return "1f1d53743f4592ee455aa3eaf9019457";
  }

  static const char* value(const ::lxind_msgs::SendDistAndAngle&) { return value(); }
};

template<>
struct DataType< ::lxind_msgs::SendDistAndAngle > {
  static const char* value()
  {
    return "lxind_msgs/SendDistAndAngle";
  }

  static const char* value(const ::lxind_msgs::SendDistAndAngle&) { return value(); }
};


// service_traits::MD5Sum< ::lxind_msgs::SendDistAndAngleRequest> should match 
// service_traits::MD5Sum< ::lxind_msgs::SendDistAndAngle > 
template<>
struct MD5Sum< ::lxind_msgs::SendDistAndAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::SendDistAndAngle >::value();
  }
  static const char* value(const ::lxind_msgs::SendDistAndAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::SendDistAndAngleRequest> should match 
// service_traits::DataType< ::lxind_msgs::SendDistAndAngle > 
template<>
struct DataType< ::lxind_msgs::SendDistAndAngleRequest>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::SendDistAndAngle >::value();
  }
  static const char* value(const ::lxind_msgs::SendDistAndAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lxind_msgs::SendDistAndAngleResponse> should match 
// service_traits::MD5Sum< ::lxind_msgs::SendDistAndAngle > 
template<>
struct MD5Sum< ::lxind_msgs::SendDistAndAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::SendDistAndAngle >::value();
  }
  static const char* value(const ::lxind_msgs::SendDistAndAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::SendDistAndAngleResponse> should match 
// service_traits::DataType< ::lxind_msgs::SendDistAndAngle > 
template<>
struct DataType< ::lxind_msgs::SendDistAndAngleResponse>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::SendDistAndAngle >::value();
  }
  static const char* value(const ::lxind_msgs::SendDistAndAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_SENDDISTANDANGLE_H
