// Generated by gencpp from file lxind_msgs/SendDistAndAngleRequest.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_SENDDISTANDANGLEREQUEST_H
#define LXIND_MSGS_MESSAGE_SENDDISTANDANGLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lxind_msgs
{
template <class ContainerAllocator>
struct SendDistAndAngleRequest_
{
  typedef SendDistAndAngleRequest_<ContainerAllocator> Type;

  SendDistAndAngleRequest_()
    : distance(0.0)
    , angle(0.0)  {
    }
  SendDistAndAngleRequest_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendDistAndAngleRequest_

typedef ::lxind_msgs::SendDistAndAngleRequest_<std::allocator<void> > SendDistAndAngleRequest;

typedef boost::shared_ptr< ::lxind_msgs::SendDistAndAngleRequest > SendDistAndAngleRequestPtr;
typedef boost::shared_ptr< ::lxind_msgs::SendDistAndAngleRequest const> SendDistAndAngleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f1d53743f4592ee455aa3eaf9019457";
  }

  static const char* value(const ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f1d53743f4592eeULL;
  static const uint64_t static_value2 = 0x455aa3eaf9019457ULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/SendDistAndAngleRequest";
  }

  static const char* value(const ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n\
float64 angle\n\
";
  }

  static const char* value(const ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendDistAndAngleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::SendDistAndAngleRequest_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_SENDDISTANDANGLEREQUEST_H
