// Generated by gencpp from file lxind_msgs/ServerInfo.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_SERVERINFO_H
#define LXIND_MSGS_MESSAGE_SERVERINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lxind_msgs
{
template <class ContainerAllocator>
struct ServerInfo_
{
  typedef ServerInfo_<ContainerAllocator> Type;

  ServerInfo_()
    : mode(0)
    , server_name()  {
    }
  ServerInfo_(const ContainerAllocator& _alloc)
    : mode(0)
    , server_name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _server_name_type;
  _server_name_type server_name;





  typedef boost::shared_ptr< ::lxind_msgs::ServerInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::ServerInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ServerInfo_

typedef ::lxind_msgs::ServerInfo_<std::allocator<void> > ServerInfo;

typedef boost::shared_ptr< ::lxind_msgs::ServerInfo > ServerInfoPtr;
typedef boost::shared_ptr< ::lxind_msgs::ServerInfo const> ServerInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::ServerInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::ServerInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::ServerInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::ServerInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::ServerInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::ServerInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::ServerInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::ServerInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::ServerInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "324d2f7cd1b2d4648d65da12545afb4f";
  }

  static const char* value(const ::lxind_msgs::ServerInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x324d2f7cd1b2d464ULL;
  static const uint64_t static_value2 = 0x8d65da12545afb4fULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::ServerInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/ServerInfo";
  }

  static const char* value(const ::lxind_msgs::ServerInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::ServerInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32  mode\n\
string server_name\n\
";
  }

  static const char* value(const ::lxind_msgs::ServerInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::ServerInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.server_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServerInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::ServerInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::ServerInfo_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    s << indent << "server_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.server_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_SERVERINFO_H
