// Generated by gencpp from file lxind_msgs/ServerReturnPackage.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_SERVERRETURNPACKAGE_H
#define LXIND_MSGS_MESSAGE_SERVERRETURNPACKAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lxind_msgs
{
template <class ContainerAllocator>
struct ServerReturnPackage_
{
  typedef ServerReturnPackage_<ContainerAllocator> Type;

  ServerReturnPackage_()
    : header()
    , package_header(0)
    , warn(0)  {
    }
  ServerReturnPackage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , package_header(0)
    , warn(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _package_header_type;
  _package_header_type package_header;

   typedef int32_t _warn_type;
  _warn_type warn;





  typedef boost::shared_ptr< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> const> ConstPtr;

}; // struct ServerReturnPackage_

typedef ::lxind_msgs::ServerReturnPackage_<std::allocator<void> > ServerReturnPackage;

typedef boost::shared_ptr< ::lxind_msgs::ServerReturnPackage > ServerReturnPackagePtr;
typedef boost::shared_ptr< ::lxind_msgs::ServerReturnPackage const> ServerReturnPackageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "425ca2618ab4a8a07e9ecad46a72601f";
  }

  static const char* value(const ::lxind_msgs::ServerReturnPackage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x425ca2618ab4a8a0ULL;
  static const uint64_t static_value2 = 0x7e9ecad46a72601fULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/ServerReturnPackage";
  }

  static const char* value(const ::lxind_msgs::ServerReturnPackage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
int8 package_header\n\
int32    warn\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::lxind_msgs::ServerReturnPackage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.package_header);
      stream.next(m.warn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServerReturnPackage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::ServerReturnPackage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::ServerReturnPackage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "package_header: ";
    Printer<int8_t>::stream(s, indent + "  ", v.package_header);
    s << indent << "warn: ";
    Printer<int32_t>::stream(s, indent + "  ", v.warn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_SERVERRETURNPACKAGE_H
