(cl:in-package lxind_msgs-srv)
(cl:export '(TASK_ID-VAL
          TASK_ID
          SUB_TASK_CMD-VAL
          SUB_TASK_CMD
          NEXT_PRITASK_CMD-VAL
          NEXT_PRITASK_CMD
          TARGET_STATE-VAL
          TARGET_STATE
          TARGET_ID-VAL
          TARGET_ID
          TARGET_NAME-VAL
          TARGET_NAME
          TOL_DIST-VAL
          TOL_DIST
          TOL_ANGLE-VAL
          TOL_ANGLE
          TO_GOAL_MODE-VAL
          TO_GOAL_MODE
          ENABLE_OA-VAL
          ENABLE_OA
          MAX_SPEED-VAL
          MAX_SPEED
          SAFE_DIST-VAL
          SAFE_DIST
          MIN_TURN_RADIUS-VAL
          MIN_TURN_RADIUS
          SHAPE_TRANSFORM-VAL
          SHAPE_TRANSFORM
          INIT_STATE-VAL
          INIT_STATE
          FIXED_PATH-VAL
          FIXED_PATH
          LOAD_MODE-VAL
          LOAD_MODE
          DIRECTION-VAL
          DIRECTION
          ALIGN_PART-VAL
          ALIGN_PART
          ALIGN_DIR-VAL
          ALIGN_DIR
          PREC_DIST-VAL
          PREC_DIST
          ROLL_PART-VAL
          ROLL_PART
          EXTRA_INFO-VAL
          EXTRA_INFO
          SUCCEED-VAL
          SUCCEED
))