camera_id : 11
fx : 373.803
fy : 373.4535
cx : 274.0965
cy : 254.181
k1 : -0.410433
k2 : 0.19425
k3 : 0
k4 : 0
k5 : -0.046885
height : 960
width :  1280
img_ratio : 2
exp_set : 100
gain_set : 20
frame_ : 30
show : false
calibration : false
write_id : false
camera_mode: 0
clear : false
board_flag : false
Tbc : false
qr_need : 4
time_out : 100000
qr_size : 20.5
qr_interval : 10
qr_initx : -0.056
qr_inity : -0.056
qr_mode : 4
point_height : 0.1
p_dot : 1
camera_x : -0.0056597
camera_y : 0.00800134
camera_yaw : 3.14868
open_camera_window : true
