// Generated by gencpp from file ifm3d/Config.msg
// DO NOT EDIT!


#ifndef IFM3D_MESSAGE_CONFIG_H
#define IFM3D_MESSAGE_CONFIG_H

#include <ros/service_traits.h>


#include <ifm3d/ConfigRequest.h>
#include <ifm3d/ConfigResponse.h>


namespace ifm3d
{

struct Config
{

typedef ConfigRequest Request;
typedef ConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Config
} // namespace ifm3d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ifm3d::Config > {
  static const char* value()
  {
    return "2ae3559b462614ae239cd0372f7a82af";
  }

  static const char* value(const ::ifm3d::Config&) { return value(); }
};

template<>
struct DataType< ::ifm3d::Config > {
  static const char* value()
  {
    return "ifm3d/Config";
  }

  static const char* value(const ::ifm3d::Config&) { return value(); }
};


// service_traits::MD5Sum< ::ifm3d::ConfigRequest> should match 
// service_traits::MD5Sum< ::ifm3d::Config > 
template<>
struct MD5Sum< ::ifm3d::ConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ifm3d::Config >::value();
  }
  static const char* value(const ::ifm3d::ConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ifm3d::ConfigRequest> should match 
// service_traits::DataType< ::ifm3d::Config > 
template<>
struct DataType< ::ifm3d::ConfigRequest>
{
  static const char* value()
  {
    return DataType< ::ifm3d::Config >::value();
  }
  static const char* value(const ::ifm3d::ConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ifm3d::ConfigResponse> should match 
// service_traits::MD5Sum< ::ifm3d::Config > 
template<>
struct MD5Sum< ::ifm3d::ConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ifm3d::Config >::value();
  }
  static const char* value(const ::ifm3d::ConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ifm3d::ConfigResponse> should match 
// service_traits::DataType< ::ifm3d::Config > 
template<>
struct DataType< ::ifm3d::ConfigResponse>
{
  static const char* value()
  {
    return DataType< ::ifm3d::Config >::value();
  }
  static const char* value(const ::ifm3d::ConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IFM3D_MESSAGE_CONFIG_H
