// Generated by gencpp from file ifm3d/Dump.msg
// DO NOT EDIT!


#ifndef IFM3D_MESSAGE_DUMP_H
#define IFM3D_MESSAGE_DUMP_H

#include <ros/service_traits.h>


#include <ifm3d/DumpRequest.h>
#include <ifm3d/DumpResponse.h>


namespace ifm3d
{

struct Dump
{

typedef DumpRequest Request;
typedef DumpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Dump
} // namespace ifm3d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ifm3d::Dump > {
  static const char* value()
  {
    return "44475fe0541e5cf305abe53be7686d7a";
  }

  static const char* value(const ::ifm3d::Dump&) { return value(); }
};

template<>
struct DataType< ::ifm3d::Dump > {
  static const char* value()
  {
    return "ifm3d/Dump";
  }

  static const char* value(const ::ifm3d::Dump&) { return value(); }
};


// service_traits::MD5Sum< ::ifm3d::DumpRequest> should match 
// service_traits::MD5Sum< ::ifm3d::Dump > 
template<>
struct MD5Sum< ::ifm3d::DumpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ifm3d::Dump >::value();
  }
  static const char* value(const ::ifm3d::DumpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ifm3d::DumpRequest> should match 
// service_traits::DataType< ::ifm3d::Dump > 
template<>
struct DataType< ::ifm3d::DumpRequest>
{
  static const char* value()
  {
    return DataType< ::ifm3d::Dump >::value();
  }
  static const char* value(const ::ifm3d::DumpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ifm3d::DumpResponse> should match 
// service_traits::MD5Sum< ::ifm3d::Dump > 
template<>
struct MD5Sum< ::ifm3d::DumpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ifm3d::Dump >::value();
  }
  static const char* value(const ::ifm3d::DumpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ifm3d::DumpResponse> should match 
// service_traits::DataType< ::ifm3d::Dump > 
template<>
struct DataType< ::ifm3d::DumpResponse>
{
  static const char* value()
  {
    return DataType< ::ifm3d::Dump >::value();
  }
  static const char* value(const ::ifm3d::DumpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IFM3D_MESSAGE_DUMP_H
