// Generated by gencpp from file ifm3d/Trigger.msg
// DO NOT EDIT!


#ifndef IFM3D_MESSAGE_TRIGGER_H
#define IFM3D_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <ifm3d/TriggerRequest.h>
#include <ifm3d/TriggerResponse.h>


namespace ifm3d
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace ifm3d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ifm3d::Trigger > {
  static const char* value()
  {
    return "86791dcf1de997ec7de5a0de7e4dcfcc";
  }

  static const char* value(const ::ifm3d::Trigger&) { return value(); }
};

template<>
struct DataType< ::ifm3d::Trigger > {
  static const char* value()
  {
    return "ifm3d/Trigger";
  }

  static const char* value(const ::ifm3d::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::ifm3d::TriggerRequest> should match 
// service_traits::MD5Sum< ::ifm3d::Trigger > 
template<>
struct MD5Sum< ::ifm3d::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ifm3d::Trigger >::value();
  }
  static const char* value(const ::ifm3d::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ifm3d::TriggerRequest> should match 
// service_traits::DataType< ::ifm3d::Trigger > 
template<>
struct DataType< ::ifm3d::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::ifm3d::Trigger >::value();
  }
  static const char* value(const ::ifm3d::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ifm3d::TriggerResponse> should match 
// service_traits::MD5Sum< ::ifm3d::Trigger > 
template<>
struct MD5Sum< ::ifm3d::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ifm3d::Trigger >::value();
  }
  static const char* value(const ::ifm3d::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ifm3d::TriggerResponse> should match 
// service_traits::DataType< ::ifm3d::Trigger > 
template<>
struct DataType< ::ifm3d::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::ifm3d::Trigger >::value();
  }
  static const char* value(const ::ifm3d::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IFM3D_MESSAGE_TRIGGER_H
