// Generated by gencpp from file lxind_msgs/Exceptions.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_EXCEPTIONS_H
#define LXIND_MSGS_MESSAGE_EXCEPTIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lxind_msgs/Exception.h>

namespace lxind_msgs
{
template <class ContainerAllocator>
struct Exceptions_
{
  typedef Exceptions_<ContainerAllocator> Type;

  Exceptions_()
    : header()
    , exceptions()  {
    }
  Exceptions_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , exceptions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::lxind_msgs::Exception_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lxind_msgs::Exception_<ContainerAllocator> >::other >  _exceptions_type;
  _exceptions_type exceptions;





  typedef boost::shared_ptr< ::lxind_msgs::Exceptions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::Exceptions_<ContainerAllocator> const> ConstPtr;

}; // struct Exceptions_

typedef ::lxind_msgs::Exceptions_<std::allocator<void> > Exceptions;

typedef boost::shared_ptr< ::lxind_msgs::Exceptions > ExceptionsPtr;
typedef boost::shared_ptr< ::lxind_msgs::Exceptions const> ExceptionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::Exceptions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::Exceptions_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::Exceptions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::Exceptions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::Exceptions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::Exceptions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::Exceptions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::Exceptions_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::Exceptions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1ee62720c4eba0ee889e14ffdbd8cf5";
  }

  static const char* value(const ::lxind_msgs::Exceptions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1ee62720c4eba0eULL;
  static const uint64_t static_value2 = 0xe889e14ffdbd8cf5ULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::Exceptions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/Exceptions";
  }

  static const char* value(const ::lxind_msgs::Exceptions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::Exceptions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
lxind_msgs/Exception[] exceptions\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: lxind_msgs/Exception\n\
Header header\n\
\n\
string module_name\n\
int32 exc_code\n\
string description\n\
\n\
## 视觉定位异常\n\
## 0: 正常\n\
## 1: 相机启动失败\n\
## 2: 图像数据为空\n\
## 3: 图像数据较老，当前时间减去图像发送时间超过100ms\n\
## 4: 长时间(3s)没有图像数据\n\
## 5: 长时间(3s)没有里程计数据\n\
## 6: 图像过曝或欠曝\n\
## 7: 地图数据读取失败\n\
## 8: 特征检测服务异常\n\
## 9: 定位初始化失败\n\
## 10: 长时间(10s)特征检测失败\n\
## 11: 偏离路径，长距离(10m)无特征\n\
## 12: 重定位超时(10s)，定位丢失\n\
## 999: 其他异常\n\
";
  }

  static const char* value(const ::lxind_msgs::Exceptions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::Exceptions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.exceptions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Exceptions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::Exceptions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::Exceptions_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "exceptions[]" << std::endl;
    for (size_t i = 0; i < v.exceptions.size(); ++i)
    {
      s << indent << "  exceptions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lxind_msgs::Exception_<ContainerAllocator> >::stream(s, indent + "    ", v.exceptions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_EXCEPTIONS_H
