// Generated by gencpp from file lxind_msgs/poseRequest.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_POSEREQUEST_H
#define LXIND_MSGS_MESSAGE_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace lxind_msgs
{
template <class ContainerAllocator>
struct poseRequest_
{
  typedef poseRequest_<ContainerAllocator> Type;

  poseRequest_()
    : get_pose(0)
    , init_pose()  {
    }
  poseRequest_(const ContainerAllocator& _alloc)
    : get_pose(0)
    , init_pose(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _get_pose_type;
  _get_pose_type get_pose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _init_pose_type;
  _init_pose_type init_pose;





  typedef boost::shared_ptr< ::lxind_msgs::poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lxind_msgs::poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct poseRequest_

typedef ::lxind_msgs::poseRequest_<std::allocator<void> > poseRequest;

typedef boost::shared_ptr< ::lxind_msgs::poseRequest > poseRequestPtr;
typedef boost::shared_ptr< ::lxind_msgs::poseRequest const> poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lxind_msgs::poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lxind_msgs::poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lxind_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lxind_msgs': ['/home/zhangchunlei/lxind_ws/src/lxind_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lxind_msgs::poseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lxind_msgs::poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lxind_msgs::poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lxind_msgs::poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcaf254239d927a9d07fdae0edf241aa";
  }

  static const char* value(const ::lxind_msgs::poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcaf254239d927a9ULL;
  static const uint64_t static_value2 = 0xd07fdae0edf241aaULL;
};

template<class ContainerAllocator>
struct DataType< ::lxind_msgs::poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lxind_msgs/poseRequest";
  }

  static const char* value(const ::lxind_msgs::poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lxind_msgs::poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 get_pose\n\
geometry_msgs/PoseStamped init_pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::lxind_msgs::poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lxind_msgs::poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get_pose);
      stream.next(m.init_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lxind_msgs::poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lxind_msgs::poseRequest_<ContainerAllocator>& v)
  {
    s << indent << "get_pose: ";
    Printer<int64_t>::stream(s, indent + "  ", v.get_pose);
    s << indent << "init_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.init_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_POSEREQUEST_H
