// Generated by gencpp from file lxind_msgs/SendInt.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_SENDINT_H
#define LXIND_MSGS_MESSAGE_SENDINT_H

#include <ros/service_traits.h>


#include <lxind_msgs/SendIntRequest.h>
#include <lxind_msgs/SendIntResponse.h>


namespace lxind_msgs
{

struct SendInt
{

typedef SendIntRequest Request;
typedef SendIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendInt
} // namespace lxind_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lxind_msgs::SendInt > {
  static const char* value()
  {
    return "65058a332cdf9eddf11f34077a0b92a4";
  }

  static const char* value(const ::lxind_msgs::SendInt&) { return value(); }
};

template<>
struct DataType< ::lxind_msgs::SendInt > {
  static const char* value()
  {
    return "lxind_msgs/SendInt";
  }

  static const char* value(const ::lxind_msgs::SendInt&) { return value(); }
};


// service_traits::MD5Sum< ::lxind_msgs::SendIntRequest> should match 
// service_traits::MD5Sum< ::lxind_msgs::SendInt > 
template<>
struct MD5Sum< ::lxind_msgs::SendIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::SendInt >::value();
  }
  static const char* value(const ::lxind_msgs::SendIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::SendIntRequest> should match 
// service_traits::DataType< ::lxind_msgs::SendInt > 
template<>
struct DataType< ::lxind_msgs::SendIntRequest>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::SendInt >::value();
  }
  static const char* value(const ::lxind_msgs::SendIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lxind_msgs::SendIntResponse> should match 
// service_traits::MD5Sum< ::lxind_msgs::SendInt > 
template<>
struct MD5Sum< ::lxind_msgs::SendIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::SendInt >::value();
  }
  static const char* value(const ::lxind_msgs::SendIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::SendIntResponse> should match 
// service_traits::DataType< ::lxind_msgs::SendInt > 
template<>
struct DataType< ::lxind_msgs::SendIntResponse>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::SendInt >::value();
  }
  static const char* value(const ::lxind_msgs::SendIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_SENDINT_H
