// Generated by gencpp from file lxind_msgs/SendCmd.msg
// DO NOT EDIT!


#ifndef LXIND_MSGS_MESSAGE_SENDCMD_H
#define LXIND_MSGS_MESSAGE_SENDCMD_H

#include <ros/service_traits.h>


#include <lxind_msgs/SendCmdRequest.h>
#include <lxind_msgs/SendCmdResponse.h>


namespace lxind_msgs
{

struct SendCmd
{

typedef SendCmdRequest Request;
typedef SendCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendCmd
} // namespace lxind_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lxind_msgs::SendCmd > {
  static const char* value()
  {
    return "43a54fa49066cddcf148717d9d4a6353";
  }

  static const char* value(const ::lxind_msgs::SendCmd&) { return value(); }
};

template<>
struct DataType< ::lxind_msgs::SendCmd > {
  static const char* value()
  {
    return "lxind_msgs/SendCmd";
  }

  static const char* value(const ::lxind_msgs::SendCmd&) { return value(); }
};


// service_traits::MD5Sum< ::lxind_msgs::SendCmdRequest> should match 
// service_traits::MD5Sum< ::lxind_msgs::SendCmd > 
template<>
struct MD5Sum< ::lxind_msgs::SendCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::SendCmd >::value();
  }
  static const char* value(const ::lxind_msgs::SendCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::SendCmdRequest> should match 
// service_traits::DataType< ::lxind_msgs::SendCmd > 
template<>
struct DataType< ::lxind_msgs::SendCmdRequest>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::SendCmd >::value();
  }
  static const char* value(const ::lxind_msgs::SendCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lxind_msgs::SendCmdResponse> should match 
// service_traits::MD5Sum< ::lxind_msgs::SendCmd > 
template<>
struct MD5Sum< ::lxind_msgs::SendCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lxind_msgs::SendCmd >::value();
  }
  static const char* value(const ::lxind_msgs::SendCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lxind_msgs::SendCmdResponse> should match 
// service_traits::DataType< ::lxind_msgs::SendCmd > 
template<>
struct DataType< ::lxind_msgs::SendCmdResponse>
{
  static const char* value()
  {
    return DataType< ::lxind_msgs::SendCmd >::value();
  }
  static const char* value(const ::lxind_msgs::SendCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LXIND_MSGS_MESSAGE_SENDCMD_H
