# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lxind_msgs/HelfCtrltask.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HelfCtrltask(genpy.Message):
  _md5sum = "2d4c57bdaa5029887424909d3750c7bd"
  _type = "lxind_msgs/HelfCtrltask"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 l_angle
float32 r_angle
float32 l_speed
float32 r_speed
 
"""
  __slots__ = ['l_angle','r_angle','l_speed','r_speed']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       l_angle,r_angle,l_speed,r_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HelfCtrltask, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.l_angle is None:
        self.l_angle = 0.
      if self.r_angle is None:
        self.r_angle = 0.
      if self.l_speed is None:
        self.l_speed = 0.
      if self.r_speed is None:
        self.r_speed = 0.
    else:
      self.l_angle = 0.
      self.r_angle = 0.
      self.l_speed = 0.
      self.r_speed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.l_angle, _x.r_angle, _x.l_speed, _x.r_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.l_angle, _x.r_angle, _x.l_speed, _x.r_speed,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.l_angle, _x.r_angle, _x.l_speed, _x.r_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.l_angle, _x.r_angle, _x.l_speed, _x.r_speed,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
