# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lxind_msgs/InitializeLocStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import lxind_msgs.msg
import std_msgs.msg

class InitializeLocStatus(genpy.Message):
  _md5sum = "5d6cace685863e5309090db1004f6f1c"
  _type = "lxind_msgs/InitializeLocStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool isSuccess
int32 weight
InitializeLoc relocInfo
================================================================================
MSG: lxind_msgs/InitializeLoc
Header header
string name
float32 x
float32 y
float32 theta
bool is_startup_reloc
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['isSuccess','weight','relocInfo']
  _slot_types = ['bool','int32','lxind_msgs/InitializeLoc']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       isSuccess,weight,relocInfo

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(InitializeLocStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.isSuccess is None:
        self.isSuccess = False
      if self.weight is None:
        self.weight = 0
      if self.relocInfo is None:
        self.relocInfo = lxind_msgs.msg.InitializeLoc()
    else:
      self.isSuccess = False
      self.weight = 0
      self.relocInfo = lxind_msgs.msg.InitializeLoc()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Bi3I().pack(_x.isSuccess, _x.weight, _x.relocInfo.header.seq, _x.relocInfo.header.stamp.secs, _x.relocInfo.header.stamp.nsecs))
      _x = self.relocInfo.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.relocInfo.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3fB().pack(_x.relocInfo.x, _x.relocInfo.y, _x.relocInfo.theta, _x.relocInfo.is_startup_reloc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.relocInfo is None:
        self.relocInfo = lxind_msgs.msg.InitializeLoc()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.isSuccess, _x.weight, _x.relocInfo.header.seq, _x.relocInfo.header.stamp.secs, _x.relocInfo.header.stamp.nsecs,) = _get_struct_Bi3I().unpack(str[start:end])
      self.isSuccess = bool(self.isSuccess)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.relocInfo.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.relocInfo.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.relocInfo.name = str[start:end].decode('utf-8')
      else:
        self.relocInfo.name = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.relocInfo.x, _x.relocInfo.y, _x.relocInfo.theta, _x.relocInfo.is_startup_reloc,) = _get_struct_3fB().unpack(str[start:end])
      self.relocInfo.is_startup_reloc = bool(self.relocInfo.is_startup_reloc)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Bi3I().pack(_x.isSuccess, _x.weight, _x.relocInfo.header.seq, _x.relocInfo.header.stamp.secs, _x.relocInfo.header.stamp.nsecs))
      _x = self.relocInfo.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.relocInfo.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3fB().pack(_x.relocInfo.x, _x.relocInfo.y, _x.relocInfo.theta, _x.relocInfo.is_startup_reloc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.relocInfo is None:
        self.relocInfo = lxind_msgs.msg.InitializeLoc()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.isSuccess, _x.weight, _x.relocInfo.header.seq, _x.relocInfo.header.stamp.secs, _x.relocInfo.header.stamp.nsecs,) = _get_struct_Bi3I().unpack(str[start:end])
      self.isSuccess = bool(self.isSuccess)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.relocInfo.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.relocInfo.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.relocInfo.name = str[start:end].decode('utf-8')
      else:
        self.relocInfo.name = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.relocInfo.x, _x.relocInfo.y, _x.relocInfo.theta, _x.relocInfo.is_startup_reloc,) = _get_struct_3fB().unpack(str[start:end])
      self.relocInfo.is_startup_reloc = bool(self.relocInfo.is_startup_reloc)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fB = None
def _get_struct_3fB():
    global _struct_3fB
    if _struct_3fB is None:
        _struct_3fB = struct.Struct("<3fB")
    return _struct_3fB
_struct_Bi3I = None
def _get_struct_Bi3I():
    global _struct_Bi3I
    if _struct_Bi3I is None:
        _struct_Bi3I = struct.Struct("<Bi3I")
    return _struct_Bi3I
