(cl:in-package lxind_msgs-msg)
(cl:export '(TASK_ID-VAL
          TASK_ID
          PRI_TASK_CMD-VAL
          PRI_TASK_CMD
          INIT_STATE-VAL
          INIT_STATE
          TARGET_STATE-VAL
          TARGET_STATE
          TARGET_ID-VAL
          TARGET_ID
          TARGET_NAME-VAL
          TARGET_NAME
          TOL_DIST-VAL
          TOL_DIST
          TOL_ANGLE-VAL
          TOL_ANGLE
          TO_GOAL_MODE-VAL
          TO_GOAL_MODE
          ENABLE_OA-VAL
          ENABLE_OA
          MAX_SPEED-VAL
          MAX_SPEED
          MIN_TURN_RADIUS-VAL
          MIN_TURN_RADIUS
          FIXED_PATH-VAL
          FIXED_PATH
          LOAD_MODE-VAL
          LOAD_MODE
          DIRECTION-VAL
          DIRECTION
          PREC_DIST-VAL
          PREC_DIST
          EXTRA_INFO-VAL
          EXTRA_INFO
))