// Generated by gencpp from file ifm3d/ConfigRequest.msg
// DO NOT EDIT!


#ifndef IFM3D_MESSAGE_CONFIGREQUEST_H
#define IFM3D_MESSAGE_CONFIGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ifm3d
{
template <class ContainerAllocator>
struct ConfigRequest_
{
  typedef ConfigRequest_<ContainerAllocator> Type;

  ConfigRequest_()
    : json()  {
    }
  ConfigRequest_(const ContainerAllocator& _alloc)
    : json(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _json_type;
  _json_type json;





  typedef boost::shared_ptr< ::ifm3d::ConfigRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ifm3d::ConfigRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigRequest_

typedef ::ifm3d::ConfigRequest_<std::allocator<void> > ConfigRequest;

typedef boost::shared_ptr< ::ifm3d::ConfigRequest > ConfigRequestPtr;
typedef boost::shared_ptr< ::ifm3d::ConfigRequest const> ConfigRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ifm3d::ConfigRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ifm3d::ConfigRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ifm3d

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ifm3d': ['/home/zhangchunlei/lxind_ws/src/lxind_drivers/ifm3d/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ifm3d::ConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ifm3d::ConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ifm3d::ConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ifm3d::ConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ifm3d::ConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ifm3d::ConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ifm3d::ConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f859d01b8e3757110b53b06e823ec597";
  }

  static const char* value(const ::ifm3d::ConfigRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf859d01b8e375711ULL;
  static const uint64_t static_value2 = 0x0b53b06e823ec597ULL;
};

template<class ContainerAllocator>
struct DataType< ::ifm3d::ConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ifm3d/ConfigRequest";
  }

  static const char* value(const ::ifm3d::ConfigRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ifm3d::ConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string json\n\
";
  }

  static const char* value(const ::ifm3d::ConfigRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ifm3d::ConfigRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ifm3d::ConfigRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ifm3d::ConfigRequest_<ContainerAllocator>& v)
  {
    s << indent << "json: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.json);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IFM3D_MESSAGE_CONFIGREQUEST_H
