// Generated by gencpp from file ifm3d/DumpRequest.msg
// DO NOT EDIT!


#ifndef IFM3D_MESSAGE_DUMPREQUEST_H
#define IFM3D_MESSAGE_DUMPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ifm3d
{
template <class ContainerAllocator>
struct DumpRequest_
{
  typedef DumpRequest_<ContainerAllocator> Type;

  DumpRequest_()
    {
    }
  DumpRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ifm3d::DumpRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ifm3d::DumpRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DumpRequest_

typedef ::ifm3d::DumpRequest_<std::allocator<void> > DumpRequest;

typedef boost::shared_ptr< ::ifm3d::DumpRequest > DumpRequestPtr;
typedef boost::shared_ptr< ::ifm3d::DumpRequest const> DumpRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ifm3d::DumpRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ifm3d::DumpRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ifm3d

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ifm3d': ['/home/zhangchunlei/lxind_ws/src/lxind_drivers/ifm3d/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ifm3d::DumpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ifm3d::DumpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ifm3d::DumpRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ifm3d::DumpRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ifm3d::DumpRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ifm3d::DumpRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ifm3d::DumpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ifm3d::DumpRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ifm3d::DumpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ifm3d/DumpRequest";
  }

  static const char* value(const ::ifm3d::DumpRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ifm3d::DumpRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::ifm3d::DumpRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ifm3d::DumpRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DumpRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ifm3d::DumpRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ifm3d::DumpRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IFM3D_MESSAGE_DUMPREQUEST_H
