// Generated by gencpp from file ifm3d/TriggerResponse.msg
// DO NOT EDIT!


#ifndef IFM3D_MESSAGE_TRIGGERRESPONSE_H
#define IFM3D_MESSAGE_TRIGGERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ifm3d
{
template <class ContainerAllocator>
struct TriggerResponse_
{
  typedef TriggerResponse_<ContainerAllocator> Type;

  TriggerResponse_()
    : status(0)  {
    }
  TriggerResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::ifm3d::TriggerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ifm3d::TriggerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TriggerResponse_

typedef ::ifm3d::TriggerResponse_<std::allocator<void> > TriggerResponse;

typedef boost::shared_ptr< ::ifm3d::TriggerResponse > TriggerResponsePtr;
typedef boost::shared_ptr< ::ifm3d::TriggerResponse const> TriggerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ifm3d::TriggerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ifm3d::TriggerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ifm3d

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ifm3d': ['/home/zhangchunlei/lxind_ws/src/lxind_drivers/ifm3d/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ifm3d::TriggerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ifm3d::TriggerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ifm3d::TriggerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ifm3d::TriggerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ifm3d::TriggerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ifm3d::TriggerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ifm3d::TriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86791dcf1de997ec7de5a0de7e4dcfcc";
  }

  static const char* value(const ::ifm3d::TriggerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86791dcf1de997ecULL;
  static const uint64_t static_value2 = 0x7de5a0de7e4dcfccULL;
};

template<class ContainerAllocator>
struct DataType< ::ifm3d::TriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ifm3d/TriggerResponse";
  }

  static const char* value(const ::ifm3d::TriggerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ifm3d::TriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n\
\n\
";
  }

  static const char* value(const ::ifm3d::TriggerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ifm3d::TriggerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TriggerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ifm3d::TriggerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ifm3d::TriggerResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IFM3D_MESSAGE_TRIGGERRESPONSE_H
